name: "Build"
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - run: docker-compose build

      - name: Tests
        run: |
          docker-compose run --rm tests \
          -e STORAGE_API_URL \
          -e STORAGE_API_TOKEN

      - name: Dump docker logs on failure
        if: failure()
        uses: jwalton/gh-docker-logs@v1
